BEGIN;

CREATE TABLE IF NOT EXISTS core.slack_department_map (
    slack_employee_id_hash CHAR(32) PRIMARY KEY,
    department_id_hash CHAR(32) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_slack_department_map_department
    ON core.slack_department_map (department_id_hash);

CREATE TABLE IF NOT EXISTS core.synthetic_identity_map (
    canonical_employee_id_hash CHAR(32) PRIMARY KEY,
    slack_employee_id_hash CHAR(32) NOT NULL UNIQUE,
    activity_employee_id_hash CHAR(32) NOT NULL UNIQUE,
    department_id_hash CHAR(32) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS features.department_monthly_slack_signal (
    department_id_hash CHAR(32) NOT NULL,
    report_month DATE NOT NULL,
    slack_cohort_employee_count INTEGER NOT NULL CHECK (slack_cohort_employee_count >= 1),
    message_count_7d BIGINT NOT NULL CHECK (message_count_7d >= 0),
    active_days_7d DOUBLE PRECISION NOT NULL CHECK (active_days_7d >= 0 AND active_days_7d <= 7),
    message_rate_7d DOUBLE PRECISION NOT NULL CHECK (message_rate_7d >= 0),
    satisfied_mean_7d DOUBLE PRECISION NOT NULL CHECK (satisfied_mean_7d BETWEEN 0 AND 1),
    neutral_mean_7d DOUBLE PRECISION NOT NULL CHECK (neutral_mean_7d BETWEEN 0 AND 1),
    frustrated_mean_7d DOUBLE PRECISION NOT NULL CHECK (frustrated_mean_7d BETWEEN 0 AND 1),
    angry_mean_7d DOUBLE PRECISION NOT NULL CHECK (angry_mean_7d BETWEEN 0 AND 1),
    dissatisfied_mean_7d DOUBLE PRECISION NOT NULL CHECK (dissatisfied_mean_7d BETWEEN 0 AND 1),
    overloaded_mean_7d DOUBLE PRECISION NOT NULL CHECK (overloaded_mean_7d BETWEEN 0 AND 1),
    conflict_mean_7d DOUBLE PRECISION NOT NULL CHECK (conflict_mean_7d BETWEEN 0 AND 1),
    disengaged_mean_7d DOUBLE PRECISION NOT NULL CHECK (disengaged_mean_7d BETWEEN 0 AND 1),
    work_strain_mean_7d DOUBLE PRECISION NOT NULL CHECK (work_strain_mean_7d BETWEEN 0 AND 1),
    message_count_30d BIGINT NOT NULL CHECK (message_count_30d >= 0),
    active_days_30d DOUBLE PRECISION NOT NULL CHECK (active_days_30d >= 0 AND active_days_30d <= 30),
    message_rate_30d DOUBLE PRECISION NOT NULL CHECK (message_rate_30d >= 0),
    satisfied_mean_30d DOUBLE PRECISION NOT NULL CHECK (satisfied_mean_30d BETWEEN 0 AND 1),
    neutral_mean_30d DOUBLE PRECISION NOT NULL CHECK (neutral_mean_30d BETWEEN 0 AND 1),
    frustrated_mean_30d DOUBLE PRECISION NOT NULL CHECK (frustrated_mean_30d BETWEEN 0 AND 1),
    angry_mean_30d DOUBLE PRECISION NOT NULL CHECK (angry_mean_30d BETWEEN 0 AND 1),
    dissatisfied_mean_30d DOUBLE PRECISION NOT NULL CHECK (dissatisfied_mean_30d BETWEEN 0 AND 1),
    overloaded_mean_30d DOUBLE PRECISION NOT NULL CHECK (overloaded_mean_30d BETWEEN 0 AND 1),
    conflict_mean_30d DOUBLE PRECISION NOT NULL CHECK (conflict_mean_30d BETWEEN 0 AND 1),
    disengaged_mean_30d DOUBLE PRECISION NOT NULL CHECK (disengaged_mean_30d BETWEEN 0 AND 1),
    work_strain_mean_30d DOUBLE PRECISION NOT NULL CHECK (work_strain_mean_30d BETWEEN 0 AND 1),
    message_count_90d BIGINT NOT NULL CHECK (message_count_90d >= 0),
    active_days_90d DOUBLE PRECISION NOT NULL CHECK (active_days_90d >= 0 AND active_days_90d <= 90),
    message_rate_90d DOUBLE PRECISION NOT NULL CHECK (message_rate_90d >= 0),
    satisfied_mean_90d DOUBLE PRECISION NOT NULL CHECK (satisfied_mean_90d BETWEEN 0 AND 1),
    neutral_mean_90d DOUBLE PRECISION NOT NULL CHECK (neutral_mean_90d BETWEEN 0 AND 1),
    frustrated_mean_90d DOUBLE PRECISION NOT NULL CHECK (frustrated_mean_90d BETWEEN 0 AND 1),
    angry_mean_90d DOUBLE PRECISION NOT NULL CHECK (angry_mean_90d BETWEEN 0 AND 1),
    dissatisfied_mean_90d DOUBLE PRECISION NOT NULL CHECK (dissatisfied_mean_90d BETWEEN 0 AND 1),
    overloaded_mean_90d DOUBLE PRECISION NOT NULL CHECK (overloaded_mean_90d BETWEEN 0 AND 1),
    conflict_mean_90d DOUBLE PRECISION NOT NULL CHECK (conflict_mean_90d BETWEEN 0 AND 1),
    disengaged_mean_90d DOUBLE PRECISION NOT NULL CHECK (disengaged_mean_90d BETWEEN 0 AND 1),
    work_strain_mean_90d DOUBLE PRECISION NOT NULL CHECK (work_strain_mean_90d BETWEEN 0 AND 1),
    message_rate_delta_7d_30d DOUBLE PRECISION NOT NULL,
    work_strain_delta_7d_30d DOUBLE PRECISION NOT NULL,
    satisfied_delta_7d_30d DOUBLE PRECISION NOT NULL,
    neutral_delta_7d_30d DOUBLE PRECISION NOT NULL,
    frustrated_delta_7d_30d DOUBLE PRECISION NOT NULL,
    angry_delta_7d_30d DOUBLE PRECISION NOT NULL,
    dissatisfied_delta_7d_30d DOUBLE PRECISION NOT NULL,
    overloaded_delta_7d_30d DOUBLE PRECISION NOT NULL,
    conflict_delta_7d_30d DOUBLE PRECISION NOT NULL,
    disengaged_delta_7d_30d DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (department_id_hash, report_month)
);

CREATE TABLE IF NOT EXISTS features.synthetic_employee_monthly_slack_signal (
    canonical_employee_id_hash CHAR(32) NOT NULL,
    department_id_hash CHAR(32) NOT NULL,
    report_month DATE NOT NULL,
    message_count_7d BIGINT NOT NULL CHECK (message_count_7d >= 0),
    active_days_7d DOUBLE PRECISION NOT NULL CHECK (active_days_7d >= 0 AND active_days_7d <= 7),
    message_rate_7d DOUBLE PRECISION NOT NULL CHECK (message_rate_7d >= 0),
    satisfied_mean_7d DOUBLE PRECISION NOT NULL CHECK (satisfied_mean_7d BETWEEN 0 AND 1),
    neutral_mean_7d DOUBLE PRECISION NOT NULL CHECK (neutral_mean_7d BETWEEN 0 AND 1),
    frustrated_mean_7d DOUBLE PRECISION NOT NULL CHECK (frustrated_mean_7d BETWEEN 0 AND 1),
    angry_mean_7d DOUBLE PRECISION NOT NULL CHECK (angry_mean_7d BETWEEN 0 AND 1),
    dissatisfied_mean_7d DOUBLE PRECISION NOT NULL CHECK (dissatisfied_mean_7d BETWEEN 0 AND 1),
    overloaded_mean_7d DOUBLE PRECISION NOT NULL CHECK (overloaded_mean_7d BETWEEN 0 AND 1),
    conflict_mean_7d DOUBLE PRECISION NOT NULL CHECK (conflict_mean_7d BETWEEN 0 AND 1),
    disengaged_mean_7d DOUBLE PRECISION NOT NULL CHECK (disengaged_mean_7d BETWEEN 0 AND 1),
    work_strain_mean_7d DOUBLE PRECISION NOT NULL CHECK (work_strain_mean_7d BETWEEN 0 AND 1),
    message_count_30d BIGINT NOT NULL CHECK (message_count_30d >= 0),
    active_days_30d DOUBLE PRECISION NOT NULL CHECK (active_days_30d >= 0 AND active_days_30d <= 30),
    message_rate_30d DOUBLE PRECISION NOT NULL CHECK (message_rate_30d >= 0),
    satisfied_mean_30d DOUBLE PRECISION NOT NULL CHECK (satisfied_mean_30d BETWEEN 0 AND 1),
    neutral_mean_30d DOUBLE PRECISION NOT NULL CHECK (neutral_mean_30d BETWEEN 0 AND 1),
    frustrated_mean_30d DOUBLE PRECISION NOT NULL CHECK (frustrated_mean_30d BETWEEN 0 AND 1),
    angry_mean_30d DOUBLE PRECISION NOT NULL CHECK (angry_mean_30d BETWEEN 0 AND 1),
    dissatisfied_mean_30d DOUBLE PRECISION NOT NULL CHECK (dissatisfied_mean_30d BETWEEN 0 AND 1),
    overloaded_mean_30d DOUBLE PRECISION NOT NULL CHECK (overloaded_mean_30d BETWEEN 0 AND 1),
    conflict_mean_30d DOUBLE PRECISION NOT NULL CHECK (conflict_mean_30d BETWEEN 0 AND 1),
    disengaged_mean_30d DOUBLE PRECISION NOT NULL CHECK (disengaged_mean_30d BETWEEN 0 AND 1),
    work_strain_mean_30d DOUBLE PRECISION NOT NULL CHECK (work_strain_mean_30d BETWEEN 0 AND 1),
    message_count_90d BIGINT NOT NULL CHECK (message_count_90d >= 0),
    active_days_90d DOUBLE PRECISION NOT NULL CHECK (active_days_90d >= 0 AND active_days_90d <= 90),
    message_rate_90d DOUBLE PRECISION NOT NULL CHECK (message_rate_90d >= 0),
    satisfied_mean_90d DOUBLE PRECISION NOT NULL CHECK (satisfied_mean_90d BETWEEN 0 AND 1),
    neutral_mean_90d DOUBLE PRECISION NOT NULL CHECK (neutral_mean_90d BETWEEN 0 AND 1),
    frustrated_mean_90d DOUBLE PRECISION NOT NULL CHECK (frustrated_mean_90d BETWEEN 0 AND 1),
    angry_mean_90d DOUBLE PRECISION NOT NULL CHECK (angry_mean_90d BETWEEN 0 AND 1),
    dissatisfied_mean_90d DOUBLE PRECISION NOT NULL CHECK (dissatisfied_mean_90d BETWEEN 0 AND 1),
    overloaded_mean_90d DOUBLE PRECISION NOT NULL CHECK (overloaded_mean_90d BETWEEN 0 AND 1),
    conflict_mean_90d DOUBLE PRECISION NOT NULL CHECK (conflict_mean_90d BETWEEN 0 AND 1),
    disengaged_mean_90d DOUBLE PRECISION NOT NULL CHECK (disengaged_mean_90d BETWEEN 0 AND 1),
    work_strain_mean_90d DOUBLE PRECISION NOT NULL CHECK (work_strain_mean_90d BETWEEN 0 AND 1),
    message_rate_delta_7d_30d DOUBLE PRECISION NOT NULL,
    work_strain_delta_7d_30d DOUBLE PRECISION NOT NULL,
    satisfied_delta_7d_30d DOUBLE PRECISION NOT NULL,
    neutral_delta_7d_30d DOUBLE PRECISION NOT NULL,
    frustrated_delta_7d_30d DOUBLE PRECISION NOT NULL,
    angry_delta_7d_30d DOUBLE PRECISION NOT NULL,
    dissatisfied_delta_7d_30d DOUBLE PRECISION NOT NULL,
    overloaded_delta_7d_30d DOUBLE PRECISION NOT NULL,
    conflict_delta_7d_30d DOUBLE PRECISION NOT NULL,
    disengaged_delta_7d_30d DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (canonical_employee_id_hash, report_month)
);

CREATE TABLE IF NOT EXISTS features.department_monthly_fusion (
    department_id_hash CHAR(32) NOT NULL,
    report_month DATE NOT NULL,
    cohort_employee_count INTEGER NOT NULL CHECK (cohort_employee_count >= 1),
    job_site_events INTEGER NOT NULL CHECK (job_site_events >= 0),
    job_site_seconds DOUBLE PRECISION NOT NULL CHECK (job_site_seconds >= 0),
    job_site_active_days INTEGER NOT NULL CHECK (job_site_active_days BETWEEN 0 AND 31),
    web_search_events INTEGER NOT NULL CHECK (web_search_events >= 0),
    web_search_active_days INTEGER NOT NULL CHECK (web_search_active_days BETWEEN 0 AND 31),
    document_usage_events INTEGER NOT NULL CHECK (document_usage_events >= 0),
    document_active_days INTEGER NOT NULL CHECK (document_active_days BETWEEN 0 AND 31),
    document_create_events INTEGER NOT NULL CHECK (document_create_events >= 0),
    document_modify_events INTEGER NOT NULL CHECK (document_modify_events >= 0),
    document_view_events INTEGER NOT NULL CHECK (document_view_events >= 0),
    after_hours_search_ratio DOUBLE PRECISION NOT NULL CHECK (after_hours_search_ratio BETWEEN 0 AND 1),
    after_hours_document_ratio DOUBLE PRECISION NOT NULL CHECK (after_hours_document_ratio BETWEEN 0 AND 1),
    weekend_search_ratio DOUBLE PRECISION NOT NULL CHECK (weekend_search_ratio BETWEEN 0 AND 1),
    weekend_document_ratio DOUBLE PRECISION NOT NULL CHECK (weekend_document_ratio BETWEEN 0 AND 1),
    slack_cohort_employee_count INTEGER NOT NULL CHECK (slack_cohort_employee_count >= 1),
    message_count_7d BIGINT NOT NULL CHECK (message_count_7d >= 0),
    active_days_7d DOUBLE PRECISION NOT NULL CHECK (active_days_7d >= 0 AND active_days_7d <= 7),
    message_rate_7d DOUBLE PRECISION NOT NULL CHECK (message_rate_7d >= 0),
    satisfied_mean_7d DOUBLE PRECISION NOT NULL CHECK (satisfied_mean_7d BETWEEN 0 AND 1),
    neutral_mean_7d DOUBLE PRECISION NOT NULL CHECK (neutral_mean_7d BETWEEN 0 AND 1),
    frustrated_mean_7d DOUBLE PRECISION NOT NULL CHECK (frustrated_mean_7d BETWEEN 0 AND 1),
    angry_mean_7d DOUBLE PRECISION NOT NULL CHECK (angry_mean_7d BETWEEN 0 AND 1),
    dissatisfied_mean_7d DOUBLE PRECISION NOT NULL CHECK (dissatisfied_mean_7d BETWEEN 0 AND 1),
    overloaded_mean_7d DOUBLE PRECISION NOT NULL CHECK (overloaded_mean_7d BETWEEN 0 AND 1),
    conflict_mean_7d DOUBLE PRECISION NOT NULL CHECK (conflict_mean_7d BETWEEN 0 AND 1),
    disengaged_mean_7d DOUBLE PRECISION NOT NULL CHECK (disengaged_mean_7d BETWEEN 0 AND 1),
    work_strain_mean_7d DOUBLE PRECISION NOT NULL CHECK (work_strain_mean_7d BETWEEN 0 AND 1),
    message_count_30d BIGINT NOT NULL CHECK (message_count_30d >= 0),
    active_days_30d DOUBLE PRECISION NOT NULL CHECK (active_days_30d >= 0 AND active_days_30d <= 30),
    message_rate_30d DOUBLE PRECISION NOT NULL CHECK (message_rate_30d >= 0),
    satisfied_mean_30d DOUBLE PRECISION NOT NULL CHECK (satisfied_mean_30d BETWEEN 0 AND 1),
    neutral_mean_30d DOUBLE PRECISION NOT NULL CHECK (neutral_mean_30d BETWEEN 0 AND 1),
    frustrated_mean_30d DOUBLE PRECISION NOT NULL CHECK (frustrated_mean_30d BETWEEN 0 AND 1),
    angry_mean_30d DOUBLE PRECISION NOT NULL CHECK (angry_mean_30d BETWEEN 0 AND 1),
    dissatisfied_mean_30d DOUBLE PRECISION NOT NULL CHECK (dissatisfied_mean_30d BETWEEN 0 AND 1),
    overloaded_mean_30d DOUBLE PRECISION NOT NULL CHECK (overloaded_mean_30d BETWEEN 0 AND 1),
    conflict_mean_30d DOUBLE PRECISION NOT NULL CHECK (conflict_mean_30d BETWEEN 0 AND 1),
    disengaged_mean_30d DOUBLE PRECISION NOT NULL CHECK (disengaged_mean_30d BETWEEN 0 AND 1),
    work_strain_mean_30d DOUBLE PRECISION NOT NULL CHECK (work_strain_mean_30d BETWEEN 0 AND 1),
    message_count_90d BIGINT NOT NULL CHECK (message_count_90d >= 0),
    active_days_90d DOUBLE PRECISION NOT NULL CHECK (active_days_90d >= 0 AND active_days_90d <= 90),
    message_rate_90d DOUBLE PRECISION NOT NULL CHECK (message_rate_90d >= 0),
    satisfied_mean_90d DOUBLE PRECISION NOT NULL CHECK (satisfied_mean_90d BETWEEN 0 AND 1),
    neutral_mean_90d DOUBLE PRECISION NOT NULL CHECK (neutral_mean_90d BETWEEN 0 AND 1),
    frustrated_mean_90d DOUBLE PRECISION NOT NULL CHECK (frustrated_mean_90d BETWEEN 0 AND 1),
    angry_mean_90d DOUBLE PRECISION NOT NULL CHECK (angry_mean_90d BETWEEN 0 AND 1),
    dissatisfied_mean_90d DOUBLE PRECISION NOT NULL CHECK (dissatisfied_mean_90d BETWEEN 0 AND 1),
    overloaded_mean_90d DOUBLE PRECISION NOT NULL CHECK (overloaded_mean_90d BETWEEN 0 AND 1),
    conflict_mean_90d DOUBLE PRECISION NOT NULL CHECK (conflict_mean_90d BETWEEN 0 AND 1),
    disengaged_mean_90d DOUBLE PRECISION NOT NULL CHECK (disengaged_mean_90d BETWEEN 0 AND 1),
    work_strain_mean_90d DOUBLE PRECISION NOT NULL CHECK (work_strain_mean_90d BETWEEN 0 AND 1),
    message_rate_delta_7d_30d DOUBLE PRECISION NOT NULL,
    work_strain_delta_7d_30d DOUBLE PRECISION NOT NULL,
    satisfied_delta_7d_30d DOUBLE PRECISION NOT NULL,
    neutral_delta_7d_30d DOUBLE PRECISION NOT NULL,
    frustrated_delta_7d_30d DOUBLE PRECISION NOT NULL,
    angry_delta_7d_30d DOUBLE PRECISION NOT NULL,
    dissatisfied_delta_7d_30d DOUBLE PRECISION NOT NULL,
    overloaded_delta_7d_30d DOUBLE PRECISION NOT NULL,
    conflict_delta_7d_30d DOUBLE PRECISION NOT NULL,
    disengaged_delta_7d_30d DOUBLE PRECISION NOT NULL,
    has_activity_data BOOLEAN NOT NULL DEFAULT TRUE,
    has_slack_data BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (department_id_hash, report_month)
);

CREATE TABLE IF NOT EXISTS features.synthetic_employee_retention_feature (
    canonical_employee_id_hash CHAR(32) NOT NULL,
    department_id_hash CHAR(32) NOT NULL,
    report_month DATE NOT NULL,
    job_site_events INTEGER NOT NULL CHECK (job_site_events >= 0),
    job_site_seconds DOUBLE PRECISION NOT NULL CHECK (job_site_seconds >= 0),
    job_site_active_days INTEGER NOT NULL CHECK (job_site_active_days BETWEEN 0 AND 31),
    web_search_events INTEGER NOT NULL CHECK (web_search_events >= 0),
    web_search_active_days INTEGER NOT NULL CHECK (web_search_active_days BETWEEN 0 AND 31),
    document_usage_events INTEGER NOT NULL CHECK (document_usage_events >= 0),
    document_active_days INTEGER NOT NULL CHECK (document_active_days BETWEEN 0 AND 31),
    document_create_events INTEGER NOT NULL CHECK (document_create_events >= 0),
    document_modify_events INTEGER NOT NULL CHECK (document_modify_events >= 0),
    document_view_events INTEGER NOT NULL CHECK (document_view_events >= 0),
    after_hours_search_ratio DOUBLE PRECISION NOT NULL CHECK (after_hours_search_ratio BETWEEN 0 AND 1),
    after_hours_document_ratio DOUBLE PRECISION NOT NULL CHECK (after_hours_document_ratio BETWEEN 0 AND 1),
    weekend_search_ratio DOUBLE PRECISION NOT NULL CHECK (weekend_search_ratio BETWEEN 0 AND 1),
    weekend_document_ratio DOUBLE PRECISION NOT NULL CHECK (weekend_document_ratio BETWEEN 0 AND 1),
    message_count_7d BIGINT NOT NULL CHECK (message_count_7d >= 0),
    active_days_7d DOUBLE PRECISION NOT NULL CHECK (active_days_7d >= 0 AND active_days_7d <= 7),
    message_rate_7d DOUBLE PRECISION NOT NULL CHECK (message_rate_7d >= 0),
    satisfied_mean_7d DOUBLE PRECISION NOT NULL CHECK (satisfied_mean_7d BETWEEN 0 AND 1),
    neutral_mean_7d DOUBLE PRECISION NOT NULL CHECK (neutral_mean_7d BETWEEN 0 AND 1),
    frustrated_mean_7d DOUBLE PRECISION NOT NULL CHECK (frustrated_mean_7d BETWEEN 0 AND 1),
    angry_mean_7d DOUBLE PRECISION NOT NULL CHECK (angry_mean_7d BETWEEN 0 AND 1),
    dissatisfied_mean_7d DOUBLE PRECISION NOT NULL CHECK (dissatisfied_mean_7d BETWEEN 0 AND 1),
    overloaded_mean_7d DOUBLE PRECISION NOT NULL CHECK (overloaded_mean_7d BETWEEN 0 AND 1),
    conflict_mean_7d DOUBLE PRECISION NOT NULL CHECK (conflict_mean_7d BETWEEN 0 AND 1),
    disengaged_mean_7d DOUBLE PRECISION NOT NULL CHECK (disengaged_mean_7d BETWEEN 0 AND 1),
    work_strain_mean_7d DOUBLE PRECISION NOT NULL CHECK (work_strain_mean_7d BETWEEN 0 AND 1),
    message_count_30d BIGINT NOT NULL CHECK (message_count_30d >= 0),
    active_days_30d DOUBLE PRECISION NOT NULL CHECK (active_days_30d >= 0 AND active_days_30d <= 30),
    message_rate_30d DOUBLE PRECISION NOT NULL CHECK (message_rate_30d >= 0),
    satisfied_mean_30d DOUBLE PRECISION NOT NULL CHECK (satisfied_mean_30d BETWEEN 0 AND 1),
    neutral_mean_30d DOUBLE PRECISION NOT NULL CHECK (neutral_mean_30d BETWEEN 0 AND 1),
    frustrated_mean_30d DOUBLE PRECISION NOT NULL CHECK (frustrated_mean_30d BETWEEN 0 AND 1),
    angry_mean_30d DOUBLE PRECISION NOT NULL CHECK (angry_mean_30d BETWEEN 0 AND 1),
    dissatisfied_mean_30d DOUBLE PRECISION NOT NULL CHECK (dissatisfied_mean_30d BETWEEN 0 AND 1),
    overloaded_mean_30d DOUBLE PRECISION NOT NULL CHECK (overloaded_mean_30d BETWEEN 0 AND 1),
    conflict_mean_30d DOUBLE PRECISION NOT NULL CHECK (conflict_mean_30d BETWEEN 0 AND 1),
    disengaged_mean_30d DOUBLE PRECISION NOT NULL CHECK (disengaged_mean_30d BETWEEN 0 AND 1),
    work_strain_mean_30d DOUBLE PRECISION NOT NULL CHECK (work_strain_mean_30d BETWEEN 0 AND 1),
    message_count_90d BIGINT NOT NULL CHECK (message_count_90d >= 0),
    active_days_90d DOUBLE PRECISION NOT NULL CHECK (active_days_90d >= 0 AND active_days_90d <= 90),
    message_rate_90d DOUBLE PRECISION NOT NULL CHECK (message_rate_90d >= 0),
    satisfied_mean_90d DOUBLE PRECISION NOT NULL CHECK (satisfied_mean_90d BETWEEN 0 AND 1),
    neutral_mean_90d DOUBLE PRECISION NOT NULL CHECK (neutral_mean_90d BETWEEN 0 AND 1),
    frustrated_mean_90d DOUBLE PRECISION NOT NULL CHECK (frustrated_mean_90d BETWEEN 0 AND 1),
    angry_mean_90d DOUBLE PRECISION NOT NULL CHECK (angry_mean_90d BETWEEN 0 AND 1),
    dissatisfied_mean_90d DOUBLE PRECISION NOT NULL CHECK (dissatisfied_mean_90d BETWEEN 0 AND 1),
    overloaded_mean_90d DOUBLE PRECISION NOT NULL CHECK (overloaded_mean_90d BETWEEN 0 AND 1),
    conflict_mean_90d DOUBLE PRECISION NOT NULL CHECK (conflict_mean_90d BETWEEN 0 AND 1),
    disengaged_mean_90d DOUBLE PRECISION NOT NULL CHECK (disengaged_mean_90d BETWEEN 0 AND 1),
    work_strain_mean_90d DOUBLE PRECISION NOT NULL CHECK (work_strain_mean_90d BETWEEN 0 AND 1),
    message_rate_delta_7d_30d DOUBLE PRECISION NOT NULL,
    work_strain_delta_7d_30d DOUBLE PRECISION NOT NULL,
    satisfied_delta_7d_30d DOUBLE PRECISION NOT NULL,
    neutral_delta_7d_30d DOUBLE PRECISION NOT NULL,
    frustrated_delta_7d_30d DOUBLE PRECISION NOT NULL,
    angry_delta_7d_30d DOUBLE PRECISION NOT NULL,
    dissatisfied_delta_7d_30d DOUBLE PRECISION NOT NULL,
    overloaded_delta_7d_30d DOUBLE PRECISION NOT NULL,
    conflict_delta_7d_30d DOUBLE PRECISION NOT NULL,
    disengaged_delta_7d_30d DOUBLE PRECISION NOT NULL,
    has_activity_data BOOLEAN NOT NULL DEFAULT TRUE,
    has_slack_data BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (canonical_employee_id_hash, report_month)
);

COMMENT ON TABLE core.slack_department_map IS
'Production mapping from already-HMAC-pseudonymized Slack employee IDs to pseudonymous departments. Raw Slack IDs and names are never stored.';
COMMENT ON TABLE core.synthetic_identity_map IS
'Synthetic-demo-only canonical mapping between pseudonymous Slack/activity identifiers. No raw source identifiers are persisted.';
COMMENT ON TABLE features.department_monthly_slack_signal IS
'Production-safe department Slack rollups. Signal means use employee-first then department averaging so high-volume individuals do not dominate the cohort.';
COMMENT ON TABLE features.department_monthly_fusion IS
'Production-safe cohort feature mart joining department Slack trends with monthly activity-report aggregates. Not an individual employment decision table.';
COMMENT ON TABLE features.synthetic_employee_retention_feature IS
'Employee-level ML-ready feature mart reserved for synthetic portfolio data only.';

INSERT INTO core.app_metadata (key, value)
VALUES ('schema_version', 'step5-feature-store-v1')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

COMMIT;
